/* ---------------- ON TAP: beer, cider, sake and the wall ----------------
   Everything a bartender pours that was brewed rather than distilled, and the
   machine that pours it. This began as the beer domain inside Behind the
   Stick, which is where it had outgrown its home: it was the largest of that
   tab's six domains and the one it opened on, while the tab's own name
   promised the half of the job that is not a cocktail.

   Two arrays, deliberately the same shape as SERVICE_STUDY and SERVICE_REF,
   so renderOnTap is renderService with two identifiers swapped, the search
   index gets two more copies of lines it already has, and one check in
   tools/check.mjs closes both.

   THE REFERENCE CARDS ARE ALL FILED UNDER 'styles'. The other four sections
   draw rows alone, which the renderer's refs.length guard already covers.

   Two beer glasses stay behind in SERVICE_REF under glassware, and that is
   not an oversight: a lesson moves when the tab answering its question moves,
   and a reference card stays where the object lives. Somebody asking what a
   nonic is should find it beside the coupe and the Nick and Nora. Every style
   card here already carries its own Glass fact, so nothing is lost. */

const ONTAP_STUDY = [
  { key:"pour", title:"The Pour", rows:[
    ["The pour itself",
     "Rinse the glass in cold water, hold it at 45 degrees, and keep the rim about an inch below the faucet so the beer lands on the wall around the midpoint of the slope — not into the bottom, not from a height. At the halfway point straighten the glass and pour into the middle so the beer falls and builds head. Finish with one to one and a half fingers of foam, call it an inch. Never let the faucet touch the beer or the inside of the glass; that's a contamination path and it's the first thing an old bartender will notice about you."],
    ["Open the faucet all the way, every time",
     "The most common self-inflicted foam problem in the trade is a faucet opened halfway. A partly open faucet throttles the beer, drops its pressure across the restriction, and the CO2 comes out of solution as foam right there in the spout. Snap it fully open in one motion and fully closed in one motion. There is no such thing as a gentle draught pour, and an eased-shut faucet drips, and a dripping faucet grows bacteria."],
    ["Head is not theft",
     "A beer with no head still has all its CO2 in solution, which means it breaks out in the guest's stomach instead of in the glass, and it means the aroma — which lives in the foam — never reaches their nose. The foam also slows the beer's contact with air while they drink it. Know the honest arithmetic though. A shaker pint is 16 oz brim-full, and an inch across the top of one is roughly five ounces of space, so a modest head puts about 14 oz of liquid in front of the guest and a full inch of foam puts closer to 12. If your menu says 'pint,' pour into a 20 oz glass or a 16 oz-to-the-line glass, or stop calling it a pint."],
    ["Why the first pour off a fresh keg foams",
     "Three things at once: the beer was agitated by the truck and the walk-in floor, the line and faucet are full of warm beer or air, and the keg has to re-equalise after tapping. Let a delivered keg rest cold — two hours minimum, overnight is the real answer — then tap it, wait a minute, and pour the first pint into the dump. Nobody pays for that one. Rolling a keg to 'settle' it does the exact opposite."],
  ] },
  { key:"glass", title:"Beer-Clean Glass", rows:[
    ["Beer-clean glass",
     "Fat is foam's enemy. Cooking grease, lipstick, a fat-based sanitizer, leftover detergent, even a fingerprint inside the rim will collapse a head in seconds and leave the beer looking and tasting dead. This is why a beer 'pours flat' far more often than the gas is actually wrong. A dirty glass ruins a perfect keg, and the guest blames the beer."],
    ["The three tests",
     "SHEETING: wet the inside of the glass — clean glass sheds water in an even sheet, filmed glass breaks it into beads. SALT: sprinkle salt on the wet interior — it clings evenly all over a clean glass and refuses to stick where there's film, so the bare patches are your map. CLING: look at a full pint — on a beer-clean glass the bubbles rise from the base in a steady bead; bubbles stuck along the wall mean film. LACING is the after-the-fact test: a clean glass keeps rings of foam down the wall as the level drops, a dirty one comes back bare."],
    ["Washing and storing glassware",
     "Beer glasses want their own sink or washer, a non-fat detergent made for glassware, and a cold rinse after. Air-dry upright on a ribbed mat so air reaches the inside — never towel-dry, never stack them on a bar towel or a flat rubber mat, which traps stale air and gives you a glass that smells like the sink. And don't freeze pint glasses for craft beer: ice crystals over-nucleate the pour into foam and freezer odor goes straight into the beer. Cold rinse instead."],
  ] },
  { key:"system", title:"The Cellar & The System", rows:[
    ["Couplers",
     "D (American Sankey) covers the great majority of US domestic and craft kegs. S (European Sankey) handles most Belgian and German imports — Stella, Heineken, Amstel. U handles Guinness, Harp and Kilkenny. A and M are German slider types — Spaten, Paulaner, Hacker-Pschorr ride the A, and G turns up on a few British ales. Brand-to-coupler lists drift as importers change, so read the keg rather than trusting your memory of a chart. The probe geometry genuinely differs — if a coupler doesn't seat with a quarter turn and a firm push down, you have the wrong one. Forcing it damages the keg valve and sprays you with about eleven dollars of beer."],
    ["Keg sizes and what they yield",
     "Half barrel: 15.5 gal, 1,984 oz, 124 sixteen-ounce pours or 165 twelves, about 160 lb full. Sixth barrel (a 'sixtel'): 5.16 gal, 661 oz, about 41 pints, roughly 60 lb — the size most craft programs live on. Quarter barrel: 7.75 gal, about 62 pints, roughly 87 lb. European 50 L: 13.2 gal, about 105 pints, about 130 lb. Budget 3 to 5 percent loss to foam and line cleaning if the system is tight. The gap between 5 percent waste and 20 percent waste is a whole free keg a month on a busy line."],
    ["CO2 and applied pressure",
     "The gas does two jobs: it pushes the beer up the line, and it keeps the beer's own carbonation dissolved. Applied pressure has to overcome line resistance plus vertical rise, and it has to match what that beer wants at your cooler temperature — usually somewhere around 10 to 14 psi on a short direct-draw system at 38F. Too high and you slowly over-carbonate the keg and everything foams. Too LOW and the beer goes flat in the keg and foams in the line, because the CO2 breaks out of solution on the way up. Memorise that one: low pressure causes foam."],
    ["Nitro",
     "Nitro beers run on beer gas, roughly 75/25 nitrogen to CO2, pushed at 30 to 40 psi off its own regulator. Nitrogen barely dissolves in beer, so you can push it that hard without over-carbonating; the CO2 fraction just holds the beer's own fizz in place. Never push a nitro keg with straight CO2 at those pressures — you'll turn a stout into a foam bomb that no amount of resting will fix. The faucet carries a restrictor plate, a disc of tiny holes, that shears the gas into microbubbles, and that's the cascade. Glass at 45 degrees, handle pulled all the way toward you for the restricted pour, fill about three-quarters, set it down and let it settle for roughly ninety seconds, then top it upright by pushing the handle away for the slow creamer pour. It takes about two minutes and there is no shortcut. It wants to be warmer than your lagers, around 42F."],
    ["38 degrees",
     "Cooler at 38F, and every foot of beer line at 38F too. Beer holds CO2 in solution as a function of temperature and pressure; warm it and the gas comes out, and it comes out inside your line where you can't see it. Above about 40F you foam on every pour. Set the box below about 34F and the coldest corner near the evaporator can drop under 28F, which is where beer actually freezes, and frozen beer never fully recovers its carbonation. When a style card says 50 to 55F, that's what the beer wants in the glass, not a second cooler setting — a pour picks up two or three degrees on the walk out and a dark beer opens up after a minute in the hand. The faucet is the warmest point in the whole system, which is exactly why the first glass after a twenty-minute lull foams and the second one is honest. One box, one temperature: 38F is a storage-and-carbonation number set by the CO2 equilibrium, not a service preference. The style temperatures in the reference entries are what the beer should be when it reaches the palate, and it gets there by warming in the glass and by your choice of glassware — never by running a second, warmer tap."],
    ["Line cleaning cadence",
     "Caustic every two weeks, recirculated, with faucets disassembled and soaked at the same time. Acid every three months to strip beerstone, which is calcium oxalate and which caustic will not touch. Couplers and FOB detectors go on the same schedule. Never put bleach in a beer line. The why: beer lines grow biofilm in days, and biofilm gives you diacetyl (butter, butterscotch), acetic sourness, or a wet-cardboard note that no amount of blaming the brewery will fix. A bar with clean lines pours a noticeably better version of the exact same beer, and it costs nothing but discipline."],
    ["FIFO on kegs",
     "Tape the delivery date on every keg the moment it hits the cooler floor, and stack so the oldest comes out first. Rough cold shelf life: macro lager 90 to 120 days, craft 45 to 60, West Coast IPA 45, hazy IPA 30 to 45. Worth knowing: most keg beer is unpasteurized even when the same brand's bottles aren't, which is why the cold chain matters more on draught than anywhere else in your building. Hazies die first and loudly, turning from citrus to onion and cardboard. Write the tap date on the keg too and note the day it blows — two months of that tells you your real depletion rate per line, which is the entire basis of ordering correctly. A keg that warmed and re-chilled has aged more than the calendar says."],
    ["When a keg blows mid-rush",
     "Tell the guest first. 'That one just blew, give me two minutes.' Then close the faucet, pull the coupler handle up to cut the gas, twist the coupler off, wipe the new keg's neck (it rode on a truck floor and it's a food-contact surface), seat the coupler with a quarter turn, push the handle down, wait thirty to sixty seconds, and pour the first pint into the dump. Never hand over the foam pour you knew was coming — that's a comp and a bad review in one move. If it was the last one, 86 it in the POS and tell the floor in the same breath, or servers will keep selling a beer you do not have."],
    ["Kegs are the heaviest thing you touch",
     "A full half barrel is about 160 lb of steel and liquid with no good handhold. Lift with your legs, tip and walk it on its chime rather than carrying it, never take one down stairs alone, and don't do any of it in canvas shoes. The injuries kegs cause aren't the frequent ones — that's cuts and slips — they're the ones that end careers, crushed feet and wrecked backs. Nothing about a Saturday rush is worth either."],
  ] },
  { key:"faults", title:"Foam & Faults", rows:[
    ["Foamy pour, in order of likelihood",
     "In order, ninety seconds total. (1) Did you open the faucet all the way in one snap? (2) Pour a full glass and dump it — if the second pours clean, it was a warm idle faucet and you're done. (3) Look at the walk-in thermometer and the door. Every tap foaming at once is almost always a propped door or a dying cooler. (4) Look at the CO2 — tank gauge for gas remaining, regulator for applied pressure against your house number. Empty tank and drifted regulator both foam. (5) Lift the keg. Light means it's blowing, and the last few pints always foam. (6) Walk the line for a kink, a warm run outside the cold, or a loose faucet. If none of that fixes it, 86 the tap, sell the can, and leave a written note for whoever cleans lines."],
    ["Flat pour, in order of likelihood",
     "(1) Pour a fresh one into a glass from a different rack. If that one heads up and laces, your glassware is the fault and you have a whole rack to rewash. (2) Check the CO2 tank and the applied pressure — a slow leak or a drifted regulator flattens a keg over a couple of days, and the beer will taste correct but go dead in the glass. (3) Check the keg's pack date and how long it's been tapped; five weeks on a slow line and the beer is just tired. (4) If it's one guest's glass and the beer has sat twenty minutes, that isn't a fault, that's physics — offer a fresh one anyway and don't lecture them about it."],
  ] },
  { key:"styles", title:"The Styles", rows:[
    ["Bottle and can service",
     "Open it in front of the guest, always — a bottle opened out of sight is a trust problem. Wipe the top of a can before opening; it's been in a warehouse and on a truck. Offer a glass alongside unless they wave it off, and for anything craft, pour it for them. Never touch the rim of the glass or the mouth of the bottle. Check dates before you sell, not after a complaint. Leave the yeast sediment in the bottom of a bottle-conditioned beer, with one exception: a hefeweizen, where the traditional move is to rouse the last inch and pour it in — and where the polite move is to ask first."],
    ["Glass by style, briefly",
     "Shaker pint for American lagers and pale ales, because it's cheap and it stacks. Nonic 20 oz for English ales. Pilsner flute or pokal where clarity and the rising bead are the show. 0.5 L weizen vase for hefeweizen, because that enormous head is the point of the style. Tulip or teku for IPAs, saisons, and anything aromatic. Chalice for Belgians, usually etched at the base to keep a steady bead going. Snifter for barrel-aged and high-ABV pours of 8 to 10 oz. Stange for kölsch. The rule under the rules: the more aroma a beer has, the more the glass should curve inward to hold it."],
    ["Counting beer against a guest",
     "A US standard drink is 0.6 oz of ethanol — a 12 oz beer at 5%. A 16 oz pour of a 7% IPA is about 1.9 standard drinks. A 10 oz Belgian tripel at 9.5% is about 1.6. Guests count glasses; you count alcohol. The table on their fourth round of double IPAs is eight drinks deep and describing it as 'just beers,' and the guest who ordered the tripel because it looked golden and light has no idea what they're holding. Say the number lightly and early — 'heads up, that one's 9.5' — because it's an easier conversation at nine than at eleven. Be honest with yourself about what the count is and isn't: it measures what you poured, not how impaired someone is, which moves with body weight, food, time and things you can't see. The count tells you when to start paying attention. Your eyes tell you the rest."],
    ["Beer glass families",
     "The straight American shaker pint is the worst common beer glass, and it is everywhere because distributors give them away. A nonic pint carries a bulge below the rim so stacked glasses don't chip each other and a wet hand has something to grip. A willi becher tapers slightly inward at the lip, holding a head and concentrating aroma, and it is the best single choice if you stock only one. A tulip's flare supports the big foam of Belgians and strong ales. A pilsner glass is tall and narrow to display color and bead. A weizen glass is tall with a bulged top to hold the enormous wheat-beer head. A snifter is for anything over roughly 9% that you want a guest to sip rather than swallow. Rinse the glass with cold water before you pour — a wet wall pours a cleaner head."],
    ["Beer temperature, by style",
     "Your draught system runs 36-38F, and that number is about the line, not the guest: cold beer holds its CO2 in solution and pours without turning to foam on the way to the faucet. What should reach the mouth is warmer and depends on the beer. Lagers and pilsners drink well at 38-45F. Pale ales and IPAs want 45-50F. Stouts, barleywines and strong Belgians want 50-55F, which sounds alarming until you taste one at 38F and find it has no nose and no middle. Cold mutes aroma and bitterness, so the colder you serve, the less the guest gets of what they paid for — which is fine for a macro lager on a hot patio and a waste on a fourteen-dollar imperial stout. The glass does the last few degrees of work on its own; you just have to not fight it."],
  ] },
];

const ONTAP_REF = [
  { dom:"styles", name:"American Lager", cat:"Lager", note:"The highest-volume category in the country, and genuinely difficult to brew well because there is nowhere for a flaw to hide. The guest ordering it is buying cold and familiar, not complexity, which is a legitimate thing to want. Pour it with the same care you'd give the IPA.",
    facts:[["ABV","4.2-5.0%"], ["Glass","16 oz shaker pint"], ["Serve","38F on draught, colder from the bottle cooler"], ["Tastes like","Corn sweetness, faint cracker malt, almost no hop — clean and cold is the whole point"], ["Sells to","The guest who says 'just a beer.' Wings, burgers, fried and spicy food"]] },
  { dom:"styles", name:"Pilsner", cat:"Lager", note:"The lager with hops: German pils runs drier and more bitter, Czech pils rounder and more golden. It is also the most fragile beer on your wall — pilsner shows staleness and dirty lines before anything else does, so when a pils tastes off, suspect your system before you blame the brewery.",
    facts:[["ABV","4.4-5.4%"], ["Glass","Pilsner flute or pokal"], ["Serve","38-45F"], ["Tastes like","Bready-cracker malt with a spicy noble-hop snap and a bone-dry finish"], ["Sells to","The lager drinker who wants flavor. Oysters, sausage, salty fried anything"]] },
  { dom:"styles", name:"Hefeweizen", cat:"Wheat", note:"The banana and clove come from the yeast, not from any fruit — a thirty-second explanation that reliably sells the second round. It throws an enormous head, and that's the style working, not a bad pour. The lemon wedge is an American addition that most Bavarians consider vandalism, so ask rather than garnishing on autopilot.",
    facts:[["ABV","4.5-5.6%"], ["Glass","0.5 L weizen vase"], ["Serve","45-50F"], ["Tastes like","Banana and clove from the yeast, soft wheat body, essentially no bitterness"], ["Sells to","Guests who say they don't like beer. Brunch, salads, sausage, roast chicken"]] },
  { dom:"styles", name:"Witbier", cat:"Wheat", note:"Genuinely spiced with coriander and dried orange peel, which is why the orange slice offends less here than elsewhere — though it's a Blue Moon marketing habit, not a Belgian tradition. Wit and hefe are both cloudy wheat beers and guests mix them up constantly: wit is spiced and tart, hefe is banana and clove.",
    facts:[["ABV","4.5-5.5%"], ["Glass","Tulip or weizen vase"], ["Serve","40-45F"], ["Tastes like","Coriander and dried orange peel over hazy wheat, tart, light, faintly creamy"], ["Sells to","White-wine drinkers. Mussels, goat cheese, salads, brunch"]] },
  { dom:"styles", name:"Pale Ale", cat:"Ale", note:"The most useful beer on any list because it's the bridge. When a guest says they want 'something with flavor but not bitter,' this is the answer every time — and it's the pour that converts a lager drinker into a regular who trusts your recommendations.",
    facts:[["ABV","4.5-6.2%"], ["Glass","Shaker pint or tulip"], ["Serve","45-50F"], ["Tastes like","Caramel malt spine under citrus and pine hops, balanced, sessionable"], ["Sells to","The guest ready to leave lager. Burgers, pizza, sharp cheddar"]] },
  { dom:"styles", name:"IPA (West Coast)", cat:"Ale", note:"Bitterness and alcohol both sharpen the perception of capsaicin, so the IPA a guest orders with the hottest wings on the menu makes the wings worse; steer them to the amber or the wheat and they'll thank you. Remember the arithmetic too: a 16 oz pour of 7% IPA is about 1.9 standard drinks and it drinks like one.",
    facts:[["ABV","6.0-7.5%"], ["Glass","Tulip or nonic pint"], ["Serve","45-50F"], ["Tastes like","Resinous pine and grapefruit, firm bitterness, dry finish"], ["Sells to","Hop chasers. Rich, fatty, salty food — but not chile heat"]] },
  { dom:"styles", name:"Hazy IPA", cat:"Ale", note:"The most perishable beer you sell. Fresh, it tastes like orange juice; six weeks later it goes onion, garlic and cardboard, and the guest blames you rather than the calendar. Order small and often, tape the pack date on the keg, and taste your own tap weekly.",
    facts:[["ABV","6.0-8.0%"], ["Glass","Tulip or teku"], ["Serve","42-48F"], ["Tastes like","Opaque and soft — mango, citrus pith, stone fruit — with bitterness dialled way down"], ["Sells to","People who bounced off West Coast IPA. Fried chicken, tacos, mango and chile"], ["Shelf life","30-45 days, the shortest on your wall"]] },
  { dom:"styles", name:"Amber / Red Ale", cat:"Ale", note:"The safest recommendation on the wall and the one nobody ever asks for by name. Reach for it when a guest wants 'something in between,' and reach for it when they're eating something hot — residual malt sweetness blunts chile heat where hop bitterness sharpens it.",
    facts:[["ABV","4.5-6.0%"], ["Glass","Shaker or nonic pint"], ["Serve","45-50F"], ["Tastes like","Toasted caramel malt, restrained hops, a sweet-leaning finish"], ["Sells to","The undecided middle. BBQ, roast chicken, burgers, genuinely spicy food"]] },
  { dom:"styles", name:"Brown Ale", cat:"Dark", note:"Dark color, light body — the single most useful thing you can tell a guest who believes dark means heavy. Straight out of a 38F box it tastes like nothing at all, so let the glass stand a minute before you walk it over, or tell the guest to give it one.",
    facts:[["ABV","4.2-5.6%"], ["Glass","Nonic pint"], ["Serve","50-55F"], ["Tastes like","Hazelnut, toffee and light chocolate, low bitterness, dry finish"], ["Sells to","Whiskey and bourbon drinkers. Roast meat, mushrooms, aged cheese, nuts"]] },
  { dom:"styles", name:"Porter", cat:"Dark", note:"The friendly dark beer: stout's flavor without the burnt-espresso edge, because porter leans on chocolate malt where stout uses roasted barley. When a guest wants a stout but finds them harsh, this is the pour that keeps them in the category.",
    facts:[["ABV","4.5-6.5%"], ["Glass","Nonic pint or tulip"], ["Serve","50-55F"], ["Tastes like","Chocolate and coffee, smooth through the finish, no sharp roast bite"], ["Sells to","Dessert, BBQ, chocolate, anything smoked"]] },
  { dom:"styles", name:"Stout", cat:"Dark", note:"Dry Irish stout is a light beer wearing a dark coat — Guinness Draught is 4.2% and about 125 calories per 12 oz, under a Budweiser and over a light lager, which is worth saying out loud to the guest who calls it heavy. On nitro it's a two-part pour: three-quarters full, roughly ninety seconds to cascade, then top upright. Imperial stout is a different animal: 8 to 10 oz in a snifter, and say the ABV out loud.",
    facts:[["ABV","3.8-5.0% dry Irish; 8-12% imperial"], ["Glass","20 oz tulip pint on nitro; snifter for imperial"], ["Serve","42-45F on nitro; 50-55F for imperial"], ["Tastes like","Roasted barley, coffee bitterness, dry finish, dense creamy head on nitro"], ["Sells to","Oysters, shepherd's pie, steak, chocolate desserts"]] },
  { dom:"styles", name:"Saison", cat:"Belgian & Sour", note:"The most food-flexible beer you sell and the easiest upsell to the table that ordered a bottle of wine last visit — 'dry, sparkling, peppery' lands with those guests every time. The bone-dry finish and heavy carbonation scrub fat off the palate the way a sparkling wine does.",
    facts:[["ABV","5.0-8.5%"], ["Glass","Tulip"], ["Serve","45-50F"], ["Tastes like","Peppery yeast, dry as chalk, high carbonation, lemon and hay"], ["Sells to","Wine drinkers, especially sparkling. Mussels, charcuterie, herbs, fried food, cheese"]] },
  { dom:"styles", name:"Sour / Gose", cat:"Belgian & Sour", note:"The bridge between your beer list and your cocktail list — pitch it as a beer that drinks like a sour and pour a taster first, because half of guests love it instantly and half find it alarming. Warn whoever cleans lines: a sour or a heavily fruited beer leaves a stubborn print, and the pilsner that follows it down that line will taste wrong.",
    facts:[["ABV","3.0-5.0%"], ["Glass","Tulip or pilsner glass"], ["Serve","40-45F"], ["Tastes like","Bracing lemon tartness; a gose adds salt and coriander on top"], ["Sells to","Cocktail drinkers and the hot-afternoon crowd. Ceviche, fried food, goat cheese"]] },
  { dom:"styles", name:"Belgian Strong (Dubbel, Tripel, Quad)", cat:"Belgian & Sour", note:"The dangerous one. A tripel is golden, effervescent and drinks like a 5% beer at 9.5%, so the guest who orders two has had a bit over three standard drinks without noticing. Serve it in a chalice at a smaller volume, say the number out loud when you set it down, and count it against them accordingly.",
    facts:[["ABV","6.5-12%"], ["Glass","Chalice or tulip"], ["Pour","8-12 oz, never a full pint"], ["Serve","45-55F"], ["Tastes like","Dubbel: raisin and caramel. Tripel: golden, spicy, deceptively light. Quad: fig, rum, warmth"], ["Sells to","Wine and spirits drinkers. Cheese boards, roast pork, rich stews"]] },
];

/* The same KNOWLEDGE bank the quiz already draws from. All nineteen carry
   topic:"ontap", which the quiz split minted for them before this move. */
KNOWLEDGE.push(
  /* --- beer --- */
  { q:"A faucet that has sat untouched for twenty minutes pours a glass of pure foam, and the next glass pours clean. Most likely cause?",
    options:["The keg is nearly empty", "The CO2 regulator has drifted too high", "Beer sitting in the warm faucet broke out of solution", "The glass came off the washer still warm"],
    a:2, topic:"ontap",
    explain:"The faucet is the warmest point in a draught system, and warm beer releases its CO2. A mis-set regulator, a blowing keg and a hot glass all foam too, but all three would foam the second pour as well — the fact that it self-corrects is the whole diagnosis." },
  { q:"The standard cooler and line temperature for a direct-draw draught system is…",
    options:["38F", "34F", "30F", "45F"],
    a:0, topic:"ontap",
    explain:"38F holds a typical 2.4 to 2.7 volumes of CO2 in solution at normal applied pressure. Colder buys you nothing and risks it: the coldest corner of a box set to 34F can dip under 28F, where beer actually freezes, and above 40F the gas breaks out inside the line and every pour foams." },
  { q:"Most American domestic and craft kegs use which coupler?",
    options:["S system", "U system", "A system", "D system"],
    a:3, topic:"ontap",
    explain:"D (American Sankey) is the US default; S covers most European imports, U the Irish stouts, A and M certain German brands. The probe geometry actually differs, so a coupler that won't seat with a quarter turn is the wrong coupler, not a stuck one." },
  { q:"A half-barrel keg holds 15.5 gallons. Roughly how many 16 oz pours is that before waste?",
    options:["165", "124", "141", "198"],
    a:1, topic:"ontap",
    explain:"15.5 gallons is 1,984 fluid ounces, or 124 sixteen-ounce pours. 165 is what the same keg yields in 12 oz servings, and 141 is the tempting wrong turn — that's the count if you divide by the 14 oz of liquid actually in a headed pint rather than by the size of the glass." },
  { q:"You wet the inside of a glass and the water breaks into beads instead of running off in a sheet. That means…",
    options:["The glass is beer-clean and ready", "The glass is colder than the beer", "Your water supply is unusually hard", "There is a fatty or detergent film on the glass"],
    a:3, topic:"ontap",
    explain:"Water sheets evenly off clean glass and beads on film. That film — grease, lipstick, or a fat-based sanitizer residue — will flatten the head on every beer you pour into it, and the guest will blame the beer." },
  { q:"A full pint has tiny bubbles clinging in patches to the inside of the glass wall. What does that tell you?",
    options:["The beer is over-carbonated", "The applied pressure is set too high", "The glass has a film on it", "The beer is perfectly conditioned"],
    a:2, topic:"ontap",
    explain:"Bubbles need a nucleation site, and on a beer-clean glass the CO2 rises in a steady bead from the base rather than sticking to the wall. Cling means film, and film means the head will collapse and the glass will come back without lacing." },
  { q:"The 'beer gas' behind a nitro stout tap is…",
    options:["Roughly 50/50 nitrogen to CO2 at 12 to 14 psi", "Roughly 75/25 nitrogen to CO2 at 30 to 40 psi", "100% nitrogen at 30 to 40 psi", "Roughly 25/75 nitrogen to CO2 at 30 to 40 psi"],
    a:1, topic:"ontap",
    explain:"Nitrogen barely dissolves in beer, so it can be pushed hard without over-carbonating the keg, while the small CO2 fraction holds the beer's own carbonation in solution. Flip that ratio and 30-plus psi of mostly-CO2 turns the keg into a foam bomb; drop to pure nitrogen and the beer slowly goes flat." },
  { q:"The correct nitro stout pour is…",
    options:["Fill about three-quarters, let it settle, then top it upright", "Fill three-quarters and top it straight away, settling in front of the guest", "Fill to the rim in one pull and let the overflow carry the foam off", "Fill halfway, wait for the cascade, then finish it at 45 degrees"],
    a:0, topic:"ontap",
    explain:"The cascade has to finish before you can build the dome, which is why the two-part pour takes about two minutes and why topping it early just collapses back on you. Handing over a still-cascading glass looks fast and drinks wrong." },
  { q:"The industry standard cleaning cadence for draught lines is…",
    options:["Caustic weekly, acid monthly", "Caustic monthly, acid yearly", "Caustic every two weeks, acid quarterly", "Caustic quarterly, acid only as needed"],
    a:2, topic:"ontap",
    explain:"Two-week caustic kills the biofilm; quarterly acid removes beerstone, which is calcium oxalate and which caustic will not touch. A bar that runs caustic faithfully and skips the acid step still ends up pouring buttery beer, and never understands why." },
  { q:"Every pour from one tap has a good head but a butterscotch or vinegar edge. The keg was tapped four days ago, and the same beer out of a can tastes fine. First suspect?",
    options:["The keg itself is past its pack date", "A slow CO2 leak has flattened the keg", "Lipstick or detergent residue on the glassware", "Bacteria and wild yeast growing in the beer line"],
    a:3, topic:"ontap",
    explain:"The can rules out the brewery and four days rules out age; an off flavor isolated to one tap lives in that tap's line, where biofilm produces diacetyl and acetic notes within days. Stale beer goes papery, not buttery, and a dirty glass kills head retention without adding flavor at all." },
  { q:"The correct glass for a hefeweizen is…",
    options:["A 0.2 L stange", "A 0.5 L weizen vase", "A 10 oz snifter", "A 16 oz shaker pint"],
    a:1, topic:"ontap",
    explain:"A hefe throws an enormous head and the tall curved vase is built to hold it, because that head is where the banana and clove aroma sits. The stange belongs to kölsch and the snifter to high-ABV dark beer." },
  { q:"A 16 oz pour of a 7% IPA counts as roughly how many US standard drinks?",
    options:["About 1.9", "About 1.3", "About 1.0", "About 2.8"],
    a:0, topic:"ontap",
    explain:"A US standard drink is 0.6 oz of ethanol, which is a 12 oz beer at 5%; sixteen ounces at 7% is 1.12 oz of ethanol. 1.3 is what you'd get if that pint were a 5% lager, and the gap between those two numbers is the whole reason you count alcohol instead of glasses." },
  { q:"SCENARIO — A guest two sips into a pint says the beer tastes flat. The pour looked normal. Your first move is…",
    options:["Check the CO2 tank and the applied pressure before anything else", "Explain that the style is naturally low in carbonation", "Pour a fresh one into a glass from a different rack and compare", "Comp it and pour them something else entirely"],
    a:2, topic:"ontap",
    explain:"Checking the gas is genuinely defensible, since a drifting regulator really does flatten a keg over a couple of days — but a film on one rack of glasses kills the head on perfectly carbonated beer, and the glass test takes fifteen seconds standing right there. If the fresh glass also falls flat, then go look at the gas." },
  { q:"SCENARIO — A keg blows mid-rush with six tickets on the rail. Best sequence?",
    options:["Finish the other five tickets first, then swap the keg quietly", "Swap it immediately and serve the first foamy pour with an apology", "86 the beer for the night and offer the table a substitute", "Tell the guest a time, swap it, dump the first pour, then serve"],
    a:3, topic:"ontap",
    explain:"Finishing the other tickets first is defensible when a barback can swap the keg for you, but if you're alone the guest whose beer stopped mid-pour is the one watching you work, and silence reads as being forgotten. Give them a number before you disappear, and never hand over the foam pint you already knew was coming." },
  { q:"SCENARIO — A keg lands off a warm truck at 4pm and you need it on tap by 6. Best move?",
    options:["Get it cold, let it rest two hours, then tap and pour one off", "Tap it now so the line has time to settle before service", "Roll it on its chime a few times to settle the beer, then tap", "Tap it now and pour off a pitcher of foam right away"],
    a:0, topic:"ontap",
    explain:"Warm agitated beer is foam, and tapping a warm keg early doesn't cool it — two hours cold is the bare minimum and overnight is the real answer. Rolling it agitates the beer further, which is the opposite of settling." },
  { q:"Guinness and Harp kegs in the US use which coupler?",
    options:["D system", "U system", "S system", "A system"],
    a:1, topic:"ontap",
    explain:"U covers the Irish stouts and ales, while D handles most American kegs, S most European imports, and A and M certain German brands. Brand lists shift as importers change, so label your odd couplers and read the keg — forcing the wrong probe geometry breaks the valve." },
  { q:"Green and clear beer bottles are a problem mainly because…",
    options:["The glass is thinner and chips more easily at the rim", "Beer oxidises faster in lighter glass regardless of light", "Clear and green bottles cannot be pasteurized after filling", "Light passes through and skunks the beer within minutes"],
    a:3, topic:"ontap",
    explain:"Brown glass blocks most of the light that reacts with hop compounds to produce the skunk thiol; a clear bottle in a sunny window can turn in under a minute. Cans have no light-strike problem at all, which is a large part of why craft beer moved to them." },
  { q:"SCENARIO — At 9pm every tap on the wall starts foaming at once. Where do you look first?",
    options:["The faucets, which probably all need new seals", "The primary regulator feeding the whole gas manifold", "The walk-in temperature and whether the door is shut", "Each keg's coupler, checking one line at a time"],
    a:2, topic:"ontap",
    explain:"Both the cooler and the primary regulator are shared causes, so both are worth suspecting — but the cooler is free to check, a door propped open during a restock is far more common than a regulator that jumps, and over-pressure needs days to over-carbonate a keg while a warm box foams within the hour. Rule out the door, then go read the primary." },
  { q:"Your draught faucets run about 38F. What temperature should actually reach the guest?",
    options:["38F across the board, in a glass out of the freezer", "Lagers 38-45F, ales 45-50F, stouts and strong ales 50-55F", "Everything at 55F, so the aromatics have room to open", "Everything at 45F, a fair compromise across every style"],
    a:1, topic:"ontap",
    explain:"Lines run cold because cold beer holds its CO2 and pours without foaming, not because 38F is the right drinking temperature for a stout. Cold mutes aroma and bitterness, so the beers you charge the most for are the ones that should warm a few degrees in the glass." },
);
