/* ============ COFFEE & TEA ============
   Nine sections, shaped exactly like ONTAP_STUDY and SERVICE_STUDY so one
   renderer pattern, one search-index pattern and one check in tools/check.mjs
   cover all three.

   This tab is REFERENCE AND VIDEO, not a drill deck. COFFEE_REF is deliberately
   absent from DECK_SOURCES, allDrinks, groupsFor and cardTicket, which is the
   older Behind the Stick shape rather than the newer On Tap one. SERVICE_REF
   has shipped that way since the beginning and nothing in either tree assumes
   otherwise: every consumer of a *_REF array names its array explicitly, and
   there is no generic loop over reference tabs. If it ever should become a
   deck source, the shape is already right and the change is a handful of lines
   in ui-study.js.

   The drinks stay where they live. This app already holds 22 coffee and tea
   cocktails, 21 zero-proof drinks under a category called Coffee, Tea & Warm,
   and 12 shots, each with its own lore. Spiked & Service indexes them and
   links out to them; it does not copy a single spec, because a cocktail name
   is a spaced repetition primary key and moving one rewrites study records.

   EVERY WORD IN THIS FILE IS WRITTEN WITHOUT AN EM DASH, on purpose. The
   monorepo counts them across the published tree against a baseline of 14 with
   nine already spent, so dash-free prose is what lets this file be byte
   identical in both trees rather than two diverging copies.
   ============ */

const COFFEE_STUDY = [
  { key:"machine", title:"The Machine", rows:[
    ["What the machine actually does",
     "Espresso is not strong coffee, which is the belief to kill first. Drip drains at atmospheric pressure and a press just steeps, but an espresso machine forces water near 200F through a compacted bed of very fine grounds, and the pressure changes what comes out. You dose a modern double basket at about 18 to 20 grams, tamp it level, lock the portafilter into the group, and run roughly twice the dose in liquid, 36 to 40 grams, in 25 to 30 seconds. Dose in against liquid out is the brew ratio, which with grind is most of your control. Nine bar, about 130 psi, is a benchmark rather than a constant: preinfusion runs below it and profiling machines move it through the shot. Tamping is argued about; level matters more than force, and the thirty pound rule has few defenders left. It carries roughly 8 to 12 percent dissolved solids against filter coffee's 1.15 to 1.35, plus emulsified oil and fine solids a paper filter strips out. Crema is roast carbon dioxide, driven into solution under pressure and foaming out as the pressure drops, so it reads freshness and blend rather than quality. Espresso is a method, not a bean or a roast level, and any coffee can run through it."],
    ["Boilers, and what the machine can do at once",
     "The only boiler question a bar has is what the machine does while ten drinks land at once, and the line that matters is whether it brews and steams together. A single boiler dual use machine cannot: you brew near 200F, flip to steam, wait for the boiler to climb, steam, then wait longer for it to fall back, and that wait is the minute you do not have. A thermoblock heats water in a metal block as it passes, storing almost nothing, so it switches quickly but steams thinly and stalls on the second milk drink. A heat exchanger holds one boiler at steam pressure, usually one to one and a half bar or about 250 to 260F, with a tube of fresh water running through it that reaches brew temperature on the way to the group, so one boiler does both, as most bar machines do. The cost is that water standing in that tube overheats while the machine idles, so flush the group before the first shot and after any long pause. A dual boiler holds each separately, buying steady brew temperature and no flush rather than extra speed. The wrong belief is that the second boiler is what saves you in a rush. What saves you is never having to choose."],
    ["Temperature is the variable nobody watches",
     "Water at the group runs between 190 and 205F, and the trade does not agree inside it: Italian certification sits low, specialty houses high, and set points move with roast, lower for dark, higher for light. The wrong belief is that the machine simply holds it. A boiler holds its set point, which is not the temperature of the water meeting your coffee. Many machines run a pressurestat, a switch that lets pressure and so temperature swing through a cycle, as a small machine's thermostat does too, so managing it by hand is not one drill: on a heat exchanger you flush the group until the standing water drops back into range, on a single boiler you surf the heating light, starting every shot at the same point in the cycle. A PID holds the point it measures to about a degree, not the puck. The group is the other half, a heavy lump of brass that has to be hot, so give it half an hour from cold, longer on a heavy one, and leave a portafilter locked in. A cold group reads sour, thin and hollow; a hot one bitter, ashy and dry. Same dose, same grind, same time, different cup: check the group before you blame the grinder."],
    ["The grinder sets what the machine cannot fix",
     "The wrong belief is that the machine is the decisive purchase and the grinder an accessory, so a better machine will rescue bad shots. Nothing downstream undoes particle size. A blade grinder chops, making dust and boulders in the same breath, and that bed cannot extract evenly: boulders give up too little because water only reaches their outsides, while dust gives up too much and packs tight enough to choke the flow, so you taste under-extraction and over-extraction in one mouthful. Burrs fracture coffee between two surfaces a set gap apart, so size becomes a setting, not an accident, and dull burrs widen the spread. Flats sit face to face, conicals turn a cone inside a ring, and the trade reads flats as clarity and conicals as body; offer that as house taste, not measured fact, since alignment, sharpness and speed move a cup more than shape does. Channelling gets pinned on grind alone, but puck prep and distribution are argued over as hard. The machine still owns temperature stability and steam. Behind a bar, retention bites hardest: grounds stranded in the chute and burr chamber mean part of your dose is the last drink's coffee, sitting in air. Purge and bin a short dose whenever the grinder has stood idle."],
    ["Water, and the scale that kills machines",
     "Two things in your water matter and most bars run them together. Hardness is calcium and magnesium. Alkalinity is bicarbonate and carbonate, the buffer that neutralises acid. Get the mechanism right: scale is not hardness alone, it is hardness and alkalinity together, because heat drives the bicarbonate over and calcium carbonate falls out on the hottest surfaces, the element, the boiler wall, the heat exchanger tube, where it insulates the element until it overheats and fails, chokes tubing and seizes valves. Hard water low in alkalinity scales far less than its hardness number suggests, so one reading tells you nothing. Alkalinity also decides the cup: too much and a bright coffee reads dull and chalky, too little and the acidity comes through thin and sour. The wrong belief is that the filter on your line is scale protection. Plain carbon takes out chlorine and off tastes and touches neither hardness nor alkalinity; only softening, dealkalising or sequestering media do, so learn what is in your cartridge. Pure is not the safe end either: water stripped bare tastes hollow, corrodes metal because nothing buffers it, and where a boiler senses level by conductivity it can read as empty and let the fill valve flood it. Treat, remineralise, then test."],
    ["Backflushing and the cleaning you cannot skip",
     "The wrong belief is that hot water through that group all day keeps it clean. Every shot leaves coffee oil on the shower screen, the dispersion block and the three-way valve, and oil is a fat, so water alone does not carry it off. It oxidises and turns rancid, bitter as old fryer oil, and no fresh coffee covers that. Backflushing locks a blind basket, one with no holes, into the group. Water cannot pass down, so the pump builds pressure in the group; the flush comes when you stop it and the valve dumps that pressure to the drain, driving the water back up through the screen and the oil out with it. So run short bursts, not one long pull. At close, brush the screen and gasket, backflush with a detergent made for espresso machines, never dish soap, rinse the blind basket, repeat with water until it runs clear, then bin the first shot. Manuals differ on how often the detergent goes in, so follow yours. Weekly, soak baskets and portafilter bodies in that detergent, handles out. A hardened gasket lets the handle sit further round than it did and water squirt from the rim mid-shot; replace it. One hard warning: never blind backflush a machine with no three-way valve."],
    ["The grinder needs cleaning too, and differently",
     "The grinder looks clean because coffee is all that goes through it, and that is the wrong belief. Bean oil films the hopper and the chute, goes rancid as it does on a shower screen, and taints every dose that passes. Keep water out of the grinding path: steel burrs rust, and grounds plus water set like cement in the throat. Everything below the hopper is cleaned dry. The hopper gets a dry wipe weekly at least, and goes to the sink only if the manual allows and it comes back bone dry. Deeper, at an interval your volume sets: unplug it, empty the hopper, run the burrs empty, lift out the upper burr, brush burrs, chamber and chute, and vacuum rather than blow, which drives fines into the bearings. Cleaning tablets stretch that interval rather than replacing the strip down, and you purge coffee after them until it runs clean. Rice is not a grinder cleaner. Then the step everybody skips: a burr that comes off will not seat exactly as before, so the setting is gone. Dial back in with scale and timer before service, tighten only while the burrs turn, not into a static bed of grounds, and purge after every adjustment because the chute holds the old grind."],
    ["Reading a machine you have never used",
     "The wrong belief is that an espresso machine is a standard appliance, one button doing the same thing everywhere. Read it before a guest is waiting. (1) Gauges: one needle is the steam boiler, which should sit inside its printed band, commonly 1 to 1.5 bar, and a needle at zero means no steam yet. The other is brew pressure, and it only reads high against a packed basket. Nine bar is the traditional target, but many machines run lower or let pressure fall through the shot, and a lever runs off a spring, not a pump, and often has no brew gauge, so learn that machine's normal. (2) Heat: is a portafilter parked in the group, and how long has it been on, because ten minutes is not enough. (3) Basket: pull it out and look. Single, double, or a dual wall pressurised basket that makes foam through one small hole and barely answers grind. (4) Grind: find the collar, note where it sits, change nothing without asking. (5) Ask the house dose and recipe, then pull one to a cup, weighing in and out and timing from the pump. Roughly double the dry weight in 25 to 30 seconds, tasting sweet, is in business. Gushing means too coarse, choking means too fine."],
  ] },
  { key:"shot", title:"The Shot", rows:[
    ["Dose, yield and ratio",
     "A shot is not a volume. It is two weights and the ratio they make. Dose is the dry coffee in the basket, weighed in grams. Yield is the liquid espresso in the cup, also weighed in grams on a scale, not read off a line in a shot glass. Ratio sets the two against each other with the dose first, so 18 grams in and 36 grams out is 1:2. You weigh the yield because crema is foam and foam is mostly gas, so two shots with identical liquid can sit at very different heights in the glass, and the crema falls while you walk the drink out. The ranges you will meet: a double basket takes 18 to 20 grams, a single 7 to 10, and a modern normale about 1:2, with houses running 1:1.5 to 1:2.5. Traditional Italian practice is a smaller dose, near 7 grams, and it is specified as a volume in the cup including crema rather than a weight, which works out longer against the dose than 1:2, not tighter. An ounce of espresso in a cocktail spec is a cocktail measure, not a brewing target. Hand over dose and yield together at shift change, because a double tells the next person nothing at all."],
    ["Time is a symptom, not a target",
     "Your machine has a timer on it, and that is the trap. A double at about 1:2 is commonly taught to land in twenty-five to thirty seconds, so the number is worth knowing, but it is a symptom, not a target. You do not set time. Time is what the bed does when water is pushed through it, and it moves with the grind, the dose, the basket, the water temperature and the pump behind them. Start the clock at the pump and stop it when the scale hits your yield, and make the bar do it the same way, because a house that starts at first drip reads shorter on the same shot, and the two numbers cannot be compared. The mistake is chasing the clock with the wrong lever: packing in more coffee, which does slow it but changes the drink you sold; leaning harder on the tamp, where the trade still argues about how much force matters once the bed is level; or cutting dead on thirty seconds whatever is in the cup. A slow shot cut at thirty seconds is short of its yield, and short is under-extracted however long it took. Hold dose and basket, move the grind. If it tastes right at thirty-four seconds, serve it."],
    ["Grind is the only dial you turn",
     "Hold the dose, the ratio and the water temperature, and move the grind. Finer means more surface area and a tighter bed, so water meets more resistance, runs slower, and takes more out. Coarser means less resistance, faster flow, less out. Fast and sour, go finer. Slow and harsh, go coarser. The span between watery and choked is narrower than the knob looks, so move in the smallest increment your grinder offers and taste before moving again. Change one thing at a time and say out loud what you changed, because a shot moved in three places teaches you nothing about any of them. Old grind sits in the burrs and the chute after every adjustment, so purge or pull a throwaway before you judge the change, or you are tasting two grinds at once. The wrong belief is that tamp, dose and time are dials too. Time is the readout you move the grind to change, not something you set. Dose is fixed by the basket, and moving it moves the ratio too. Tamp is the one the trade still argues about, some houses drilling a fixed pressure and others holding that past a level, compacted bed more force changes little, so tamp the same way every time instead of reaching for it."],
    ["Distribution and tamping",
     "Water goes wherever it meets the least resistance, so your job is to make every part of the puck equally hard to get through. That is a distribution problem first, a tamping problem second. Grinders throw clumps, so break them up and level the bed before you tamp; stirring the dry grounds with fine needles, the tool the trade calls a WDT, does more for a shot than any amount of arm. Then tamp, and here is what people have backwards. Once the bed is consolidated it barely compresses further, and the pump pushes far harder than your arm, so firm and heroic end up much the same. Level against tilted is the gap that matters: tilt the tamper and one side of the bed is left looser, and water takes that side, not the one you pressed. The trade has repeated thirty pounds of force for decades; read that as a description of firm, not a number you could hit without a scale under the tamper. Press straight down, the same way every time, and stop. Harder does not make it stronger, and your wrist pays for it. The trade still argues how much of channelling is tamp rather than grind, dose or basket, so make yours the one thing that never varies."],
    ["Channelling, and how to see it",
     "Channelling is water finding a crack and taking it. Instead of pushing evenly through the bed it carves a route, over-extracting along it while the coffee either side is barely touched, which is why the shot tastes sour and harsh at once and finishes thin. Usually it runs fast, since the channel is the path of least resistance, blonding early and hitting yield early, and grinding finer to slow it often channels the next one. The trap is the quiet case: a shot that lands in a normal window, eighteen grams in to thirty six out in twenty five to thirty seconds, and still tastes broken. Time and weight say a shot was normal, not that it was even. A bottomless portafilter, also called naked, has no spouts, so the basket underside shows. Healthy looks like drips across the whole surface drawing into one dark steady stream, the mouse tail. Channelling sprays sideways, jets from one spot, or goes pale on one side while the rest stays dark. Check the bed first: (1) clumpy distribution, (2) a tilted tamp, (3) a knock after tamping, (4) grounds on the rim breaking the seal, (5) a dose the basket cannot take, high or low. Grind can contribute, but fix the bed before you chase it."],
    ["Sour and bitter are the two directions of extraction",
     "Coffee gives up its solubles in a rough order: acids and salts early, then the compounds that read as sweet, then the bitter, drying ones last. So extraction fails in two directions. Under-extracted, you stopped too early in that order: sour and sharp, salty at the edges, thin, and it quits the second you swallow. Over-extracted, you ran past the sweet middle: bitter, ashy, hollow, drying on the tongue, with a finish that will not leave. The 18 to 22 percent extraction target you will hear quoted came from filter brewing, and whether it fits espresso is argued, so do not repeat it as a rule. Learn both faults before service, one shot ground far too coarse and one far too fine, because you cannot recognise a fault you have never tasted. Extraction is not strength: a well extracted shot can still be too concentrated for the guest, and that is ratio, not grind. Extraction is also not the only fault, because a dark roast, stale beans, a dirty machine or scorched milk all arrive bitter with the grind innocent. Guests say bitter for anything unpleasant, so when a coffee comes back do not pull it weaker or bury it in milk on the word alone. Taste it yourself and name the fault."],
    ["Dialling in, as a procedure",
     "Here is the loop for a new bag at open. (1) Weigh a dose your basket is built for and keep it there, because you change one thing at a time. (2) Pick the target yield from the ratio, 1:2 to start, so 18 grams in and 36 out. (3) Guess the grind from where the last bag lived, coarser if this one is fresh and still gassing, finer if it is roasted lighter, because a harder bean grinds coarser. (4) Purge a few grams so you are not grinding the last bag. (5) Distribute, tamp level, lock in and pull straight onto a scale, stopping at the target yield and noting the time. (6) Taste it, then taste it in the milk drink your bar sells, because a thin shot vanishes under steamed milk. (7) Sour and fast, one step finer. Harsh and slow, one step coarser. If it sprays or gushes, suspect the puck before the grinder and repull first. (8) Purge and run the loop again. Stop when two in a row taste good and taste alike, not when the clock reads a number you like. Expect to bin several shots, then dial again when the room changes and on the next bag."],
    ["Ristretto, normale, lungo",
     "Same dose, same puck, different yield. Ristretto means restricted, roughly 1:1 to 1:1.5, so 18 grams into a double basket and 18 to 27 grams out, weighed not eyeballed. Normale is about 1:2. Lungo means long, roughly 1:3 to 1:4, so that same 18 grams pushed out to 54 or 72 grams. Now the wrong belief: a lungo is not an espresso with water added. That drink is an americano, and diluting after the fact lowers concentration without changing how much came out of the grounds. A lungo is more water forced through the same coffee, and the water arriving last carries the bitter, drying end, so it is less concentrated and more extracted at once, which is why it often reads harsh and thin rather than gentle. Most houses grind coarser for it. A ristretto runs the other way: you stop before that drying end arrives, so it is less extracted but more concentrated, which is the intensity a guest means by stronger, though less water through the puck means slightly less total caffeine. Send the guest who wants it milder to the americano, never to the lungo. The trade does not fully agree on the words, and some bars still call a watered shot a lungo, so confirm what your house means."],
    ["Freshness, degassing and the bag date",
     "The wrong belief is that fresher is always better and that the date on the bag settles it. Roasting loads the bean with carbon dioxide, and it takes days to leave. Pull coffee too soon off the roast and the gas fights you: the puck sputters and channels, the same grind setting will not repeat, and the cup reads sharp and thin because gas keeps water off the coffee. Thick crema here is gas and roast level, not quality. So coffee wants a rest, commonly 7 to 14 days off roast for espresso and longer than filter asks for, though dark roasts are often ready sooner and light ones want longer. It then holds for weeks. Once the bag is open the clock speeds up, because the enemy is oxygen rather than gas, so keep it whole bean, sealed, cool, dark, and out of the fridge, which is damp and full of smells. The one-way valve lets gas out without letting air in, so it tells you the bag is built for coffee that still gasses, not that this one is fresh. A best-by date is the roast date plus an offset the roaster chose, so ask for the offset and write the real date on the bag yourself."],
    ["Decaf is not an afterthought",
     "Decaf gets pulled last, on your regular settings, by somebody who has stopped caring, and it is the one order most likely to have a medical reason sitting behind it. Start with what happened to the bean. Every method begins by wetting green coffee, by soaking or steaming, and then carries the caffeine off with a solvent such as methylene chloride or ethyl acetate, with pressurised carbon dioxide, or with water and green coffee extract, as the Swiss Water and Mountain Water processes do. All of it swells the bean and leaves it more brittle and more porous. Brittle means it shatters into more fines at the same setting, which is why the usual starting move on espresso is coarser, but enough bars find the opposite that you dial decaf in on its own and let the shot decide. Porous means it stales faster, so buy smaller bags more often. It also roasts darker, so colour will lie to you about the roast level. If one grinder does both, grind a dose and bin it before you grind theirs, or the first shot is not decaf. And it is not caffeine free: the standard commonly quoted is at least 97 percent of the caffeine removed, so tell a guest nearly none and never zero."],
  ] },
  { key:"milk", title:"Milk & Latte Art", rows:[
    ["What steaming actually does to milk",
     "The wrong belief is that steaming is heating and that foam is a side effect of the heat. Steam does two jobs and you steer them separately. The first is stretching, also called aeration: the jet drags air through the surface and shears it into bubbles, and that stage ends early, while the milk is still cool. The second is texturing, or rolling: the same jet spins the milk hard enough to break those bubbles smaller and fold them under, which is what gets you microfoam instead of froth. Heat is not doing either job; it is your clock. What holds a bubble open is protein: the whey proteins unfold on the surface of each bubble and knit into a film, and casein helps hold it. Fat lends the body you read as creamy but builds no structure, and it costs volume, which is why skim foams bigger and drier. As for sweetness, you make no sugar and, with no lactase in the pitcher, break none down, so the roughly five percent lactose is what it always was. Warmth is credited with lifting perceived sweetness, but that is not settled, so do not sell it as chemistry. Take it too far and those proteins turn eggy, and cooked is not sweet."],
    ["The temperature ceiling",
     "The wrong belief is that hotter is better service, that steaming splits lactose into something sweeter, and that a scalded pitcher can be rescued by re-steaming or by a fresh shot over it. Work a band: cut the steam near 135F to 140F, let carryover walk it up a few degrees, and serve between 140F and 155F. That band is where the milk reads sweetest, where the foam still pours a pattern, and where the cup is still hot at the last sip. Reads is the honest word: steaming makes no new sugar and breaks no lactose down, so only your perception moves. Past roughly 160F the whey protein that was holding your bubbles finishes unfolding and cross-links to itself: the bubbles coarsen and the foam separates, and sulfur compounds come off as the boiled, faintly eggy note nobody orders. Blame heat for that, not for stiff dry foam, which is usually too much air. Here is the part people refuse. It does not come back. Cross-linked protein does not re-fold, and re-steaming only spends more heat on milk that already spent it. For extra hot, say plainly it will taste flatter, take it to that same ceiling and no further, in a handled cup. Dump anything you cooked."],
    ["Stretch, then spin",
     "The wrong belief is that you find one right spot and hold it. There is an air phase, a spin phase, and a move between them. (1) Purge the wand, then set the tip just under the surface and off center, so the jet drives a whirlpool around the wall. (2) Open the valve in one motion rather than feathering it, because jet force is what turns that whirlpool. Wide open suits a commercial boiler; low pressure wands and small volumes are often easier part open, so let the house machine decide. (3) Stretch. You want a steady tearing sound, a rhythmic tss tss, each chirp one bite of air. A shriek means the tip has broken the surface and is making big dry bubbles, not microfoam. The milk rises as it takes air, so the pitcher comes down to keep that depth. (4) Stop the air early, while the pitcher still reads cool against your palm, which holds near 100F. Air added later has no spin time left to break it down. (5) Sink the tip deeper until the hiss is gone and only a low rumble remains. That is texturing, folding the foam back through the milk, and it runs until the pitcher is too hot to hold."],
    ["The vortex, and what it is for",
     "The wrong belief is that the whirlpool is showmanship. It is the mechanism: bubbles get smaller while the steam runs or not at all, because tapping and swirling afterwards only pop the worst of what is left. The air you added in the stretch went in at mixed sizes; the spin drives the surface down and folds it under, and the shear at the jet tears the big ones apart and keeps tearing them for the rest of the steam. It also mixes the jug, because milk that is not moving stratifies: scalded where the jet sits, cool at the base, dry foam on top. To find it, put the tip off the center axis, between the middle and the wall and touching neither, and go deep enough that the surface dimples and turns rather than sputters. Some trainers tilt the pitcher for it and some keep it flat; your wand angle and jug settle that, so copy your own bar. You should see the whole body of milk turning. Without it you get a stiff cap of foam on thin milk that will not pour: the foam hangs back at the spout, then arrives all at once as a white blob on a beige cup, and no wrist saves it."],
    ["Pitcher, volume and the pour window",
     "The wrong belief is that steaming extra is thrift. Size the pitcher to the drink, not to the shift. The common pair is a twelve ounce and a twenty ounce, and the working fill is just below where the spout begins, because milk gains volume. That is a ceiling, not a target: too little in a big pitcher and the milk is too shallow to keep the tip submerged and spinning a vortex, and it overheats before you texture it. Go over and you wear it. The number on the pitcher is not the milk you pour, so measure yours to the spout once: the twelve covers one small drink, the twenty a large one or two at once. Then the real rule: never steam more than you are about to pour. What is left is not milk you saved, it is a different liquid. Its whey proteins denatured on the first heating and that does not reverse, and air folds in only while the milk is still cold, so re-steamed milk gives coarse bubbles that collapse, with the cooked note still in it. Topping cold milk up with the leftover warms the jug out of the foaming window, and raises a food safety question. Pour what you made and dump the rest."],
    ["Reading finished milk",
     "The wrong belief is that good foam stands up and a spoon should hold it. Stiff, spoonable foam is an older cappuccino style, and a guest who orders a dry cappuccino still means exactly that, but stiff foam will not pour a pattern and will not fold into the drink. What you want everywhere else is microfoam, and it looks like wet paint: a glossy, mirror-bright surface with a slight bulge, moving as one heavy liquid. If you can pick out an individual bubble, it is too big. Two moves finish it. If large bubbles are sitting on top, knock the base of the pitcher on the bench once or twice to burst them, firmly rather than hard, since a real bang drives out foam you steamed on purpose. Then swirl, and keep swirling, until the surface turns over on itself like glossy house paint being stirred. The swirl is the move that matters: foam is lighter than the milk under it and begins climbing off the moment the steam stops, and swirling folds it back in. That is the clock you are on, so do not park the pitcher and walk away. Steam, tap, swirl, wipe and purge the wand, swirl again, pour."],
    ["The pour: height, flow and the wiggle",
     "The wrong belief is that latte art comes from the wrist. The wrist only shapes white that is already floating; height and flow decide whether any white reaches the surface, and no pour saves badly textured milk. Every pattern runs the same way. (1) Swirl the pitcher until the milk is one glossy liquid, swirl the crema even, tilt the cup toward you, hold the spout high and pour a thin stream into the middle. That fall gives the stream speed to drive under the crema, so no white shows yet; white early means you are too low. (2) Somewhere between half and two thirds full, drop the spout almost onto the surface and open the flow. The stream now falls no distance and arrives with no downward speed, so the foam stays where it lands. Come down earlier for a rosetta or tulip, later for a single heart. (3) Level the cup as it fills, so nothing runs over the low rim and the whole surface opens up; hold your distance by moving the pitcher. (4) Lift and thin the stream to finish, cutting through what you made because a raised thin stream digs in again. A wiggle is side to side oscillation at a steady flow, not a speed change."],
    ["The heart is floated, not drawn",
     "The wrong belief is that a heart is drawn. Nothing is drawn. You float a circle and then cut it once, which is why most houses teach it first and why it tests your milk before your hand: foam that is stiff, bubbled or thin will not float as a clean disc, and no wrist rescues that. (1) Tilt the cup toward you, pour from height into the deep side and keep mixing until the surface is an even brown and the cup is most of the way full. (2) Drop the spout onto the surface, hold it there and open the flow up. A white disc surfaces and spreads. (3) Hold still, do not wiggle, keep pouring and let the disc push out while you bring the cup level. (4) When it nearly reaches the far rim, lift the pitcher a little, thin the stream and drive it straight through the middle of the disc and out over the far edge, then lift away. The point forms where you lift out, not where you started. The common failure is dropping in too early: with the cup still shallow the stream plunges and folds the foam under instead of leaving it on top, and the cup comes out beige."],
    ["Rosetta and tulip",
     "The wrong belief is that the rosetta and tulip are separate skills learned after the heart. Both are the heart pour with one thing added, both finish the same way, and neither appears if your foam is wrong: too thin and it sinks, too stiff and it plops. For the rosetta, everything before the white surfaces is the heart. Then, spout almost touching the surface at the far side, you wiggle: a tight side to side oscillation at steady flow while you draw the pitcher slowly back toward yourself. Each pass lays a crescent and pushes the one before it toward the far rim, so the fan opens as you retreat. At the near rim, lift, thin the stream and cut straight through it all to the far side. That line is the stem and it pulls every leaf into shape. The tulip swaps the wiggle for stops: pour a blob, cut the flow, shift back, pour a second that shoves the first away, two or three times, then cut through the lot. Stacked pulses, not one stream. Trainers differ on whether a tulip stops dead or only pauses, so follow your house. Practice off the ticket, on cheap milk or on water with a drop of dish soap, and expect blobs first."],
    ["Alternative milks, and what they do differently",
     "The wrong belief is that oat is just milk, and that non-dairy on a carton answers an allergy question. Dairy foam is held up by milk protein; most plant milks carry less, and soy, which comes close to dairy, has a different protein, so they lean on added oils, gums and stabilizers. A barista version is that milk reformulated to foam and survive espresso, so brand matters more than plant. Soy has the most protein of the three and foams stiffly, oat is what most bars find most forgiving, almond has the least and collapses fastest, though the trade disagrees on that order. Expect a shorter pour window than dairy and a cooler finish, nearer 130F to 140F, past which the foam breaks and a cooked taste comes up. Splitting is acid plus heat, soy and almond go first, so keep the shot fresh and hot, and where the build allows pour the shot into the milk rather than milk onto a standing shot. Say what you stock and that it tastes different. An allergy question is medical: some cartons reading non-dairy still contain milk-derived caseinate, and a shared wand or pitcher is cross contact, so read the carton, follow the house allergen procedure, ask a manager, and never answer from memory."],
  ] },
  { key:"filter", title:"Filter & Cold Brew", rows:[
  ] },
  { key:"tea", title:"Tea Service", rows:[
  ] },
  { key:"leaf", title:"The Leaf", rows:[
  ] },
  { key:"matcha", title:"Matcha & Chai", rows:[
  ] },
  { key:"spiked", title:"Spiked & Service", rows:[
  ] },
  { key:"faults", title:"Faults", rows:[
  ] },
];

/* Reference cards, filed by `dom` against a section key above. A card whose
   dom names no section renders nowhere and searches to a dead route, which is
   why tools/check.mjs closes that loop. */
const COFFEE_REF = [
  /* The drinks a bar actually sells. Filed under the section that explains
     them: the black ones under The Shot, the milk ones under Milk & Latte
     Art, because that is where a reader who does not know the difference
     between a cortado and a flat white will be standing. */
  { dom:"shot", name:"Espresso", cat:"Black", note:"Espresso is not a bean and not a roast level. It is a method: roughly nine bar of pressure driven through a fine, tamped bed. Any coffee can be pulled as espresso, and a bag stamped espresso roast is a roaster's suggestion, not a category. So when a guest asks what espresso you use, they are asking about the bean. Answer with the origin and the roast.",
    facts:[["Ratio","18 to 20 g in, 36 to 40 g out on the scale, 25 to 30 seconds, for the modern double. The older Italian single runs about 7 g for roughly 25 mL in the cup, and that is a volume including the crema rather than a weight. The range comes from basket size and roast: light roasts are harder to extract and usually want a finer grind and the long end of the pull."], ["Volume","1.2 to 1.4 oz (36 to 40 mL) for the double, weighed rather than eyeballed, because the crema makes the cup look fuller than the number; a traditional single is about 0.85 oz (25 mL)"], ["Milk","None"], ["Glass","Warmed demitasse, 2 to 3 oz, taken off the top of the machine where it has been sitting hot"], ["Serve","Brew water 195 to 205F, and it lands in the cup well below that. Spoon on the saucer, a glass of still water beside it, and walk it out the moment it is pulled, because crema is a foam and it thins as it stands"], ["Tastes like","Syrupy and dense under the crema, sweet through the middle, a bitter edge at the back; citrus and berry from light roasts, cocoa and nut from dark"], ["Sells to","After dinner, to the guest killing ten minutes at the bar, and to every cook and server before and after a shift. In Italy this is what a guest means by caffè, with no other word attached"]] },
  { dom:"shot", name:"Ristretto", cat:"Black", note:"Ristretto means restricted, not strong. You cut the shot early, keeping the acids and sugars that come out first and leaving more of the bitter compounds in the puck. From the same dose that means slightly less total caffeine than a full shot, not more. It tastes more intense only because it is more concentrated per sip, which is a different claim.",
    facts:[["Ratio","Same dose as your double, 18 to 20 g in, but 25 to 30 g out, which is a quarter to a third less liquid from the same coffee. Cut a normal grind early and it runs 20 to 25 seconds; grind finer for it, as some houses do, and it takes the same 25 to 30 seconds as a full shot."], ["Volume","About 0.85 to 1 oz (25 to 30 mL)"], ["Milk","None"], ["Glass","Warmed demitasse, 2 to 3 oz. It will sit barely a third full, and it is meant to"], ["Serve","Brew water 195 to 205F. Straight over with no water back unless the guest asks, because it is two swallows and nobody lingers over it"], ["Tastes like","Thick and sweet up front, bright acidity, a short finish, and noticeably less bitter than a full shot. Syrup rather than coffee"], ["Sells to","To the guest who says espresso is too bitter, and as the base shot in a piccolo. Some Australasian bars build a flat white on it too, though what a flat white is remains an open argument in the trade"]] },
  { dom:"shot", name:"Lungo", cat:"Black", note:"A lungo is not an Americano. Every drop goes through the bed under pressure, so you are extracting further into the puck rather than diluting a finished shot, which is where the bitterness and the drying finish come from. It is more dilute in the cup than an espresso and carries more total caffeine than one, from the same dose. Thinner per sip is not less coffee.",
    facts:[["Ratio","18 to 20 g in, 50 to 60 g out, roughly 30 to 45 seconds. Some houses push out to 70 g. The range is how far you are willing to go before the cup turns hollow and drying, so taste the far end before you set it."], ["Volume","1.7 to 2 oz (50 to 60 mL), and nearer 2.4 oz (70 mL) where the house pulls to the far end"], ["Milk","None"], ["Glass","Warmed cup at the 3 oz end of your demitasse range, filled higher than an espresso"], ["Serve","Brew water 195 to 205F. Goes out alone; there is enough liquid in it that a water back is not expected"], ["Tastes like","Thinner and longer than espresso, more bitterness, a drying papery finish, and the bean's darker notes pulled forward over its fruit"], ["Sells to","To the guest who wants espresso to last more than two sips but will not accept an Americano, and to capsule machine drinkers used to a button marked lungo"]] },
  { dom:"shot", name:"Americano", cat:"Black", note:"An Americano is a shot lengthened with hot water poured onto it, and that incoming water breaks the crema, which is what separates it from a long black built in the other order. The bigger thing to hold: a large Americano is not a stronger coffee. It carries exactly the caffeine of the shots in it, so when a guest wants more, sell another shot rather than a bigger cup.",
    facts:[["Ratio","A double, 18 to 20 g in and 36 to 40 g out in 25 to 30 seconds, then 4 to 6 oz of hot water poured on after. That is about 1 part espresso to 3 parts water in a small cup and closer to 1 to 4 or 5 in a large one, and the range is cup size and how the guest drinks it."], ["Volume","About 5.25 to 7.5 oz (155 to 220 mL) finished"], ["Milk","None. Milk and cream go on the side and the guest decides"], ["Glass","Warmed 8 oz cup or mug. For an iced one use a cold glass and plenty of ice, never a cup off the top of the machine"], ["Serve","Hot water straight off the machine's tap, which on many machines runs closer to boiling than to brew temperature, so this lands hotter than any milk drink and may genuinely need a minute. Leave half an inch of headroom so it carries and so there is room for milk"], ["Tastes like","Clean and long, closer to filter coffee than to espresso, with the shot's body still under it and the crema broken up by the pour rather than sitting as a layer"], ["Sells to","All day, to the black coffee drinker when you have no brewer running, and to anyone who found the drip pot empty at two in the afternoon"]] },
  { dom:"shot", name:"Long Black", cat:"Black", note:"The wrong belief is that a long black is just an Americano with an accent. Water into the cup first, shot pulled onto it, and the crema arrives as a layer the guest drinks through instead of being broken by the pour. The second difference is size: less water on the same shot, so it stays denser to the bottom. How much survives past the first sip is argued about, so taste both yourself.",
    facts:[["Ratio","Hot water first, 3 to 4 oz of it, then a double pulled straight onto it, 18 to 20 g in for 36 to 40 g out in 25 to 30 seconds. Where the house pulls ristretto instead, the same dose gives 25 to 30 g out and a denser cup. Australian and New Zealand practice sits tighter and shorter than an Americano."], ["Volume","About 4.25 to 5.5 oz (125 to 165 mL) finished, deliberately smaller than an Americano"], ["Milk","None"], ["Glass","Warmed 6 oz cup, about three quarters full on the short build and near the brim on the long one"], ["Serve","Hot water off the tap into the cup first, hotter than brew temperature on most machines, then the shot pulled directly onto it, and out immediately while the crema is still whole. Like the Americano it arrives very hot, so do not rush the guest into the first sip"], ["Tastes like","Fuller and more aromatic than an Americano on the first sip, because you drink through the crema; the bitterness arrives later as it settles"], ["Sells to","To Australian and New Zealand guests, who mostly arrive with a fixed idea of it, and to anyone who wants an Americano with more of the shot left in it"]] },
  { dom:"milk", name:"Macchiato", cat:"With Milk", note:"Macchiato means stained, and it is the espresso being stained, not the milk. A latte macchiato inverts it: a tall glass of steamed milk marked with the shot last, layered and pale. The flavored syrup drink on a chain menu is a third thing, closer to a vanilla latte. So ask which one the guest means, because the three arrive in different glasses at different sizes.",
    facts:[["Ratio","A double, 18 to 20 g in, 36 to 40 g out, 25 to 30 seconds, then marked with milk. In Italy the caffè macchiato is usually built on a single instead. The range is simply whether your bar owns a single basket or runs doubles only."], ["Volume","1.7 to 2.4 oz (50 to 70 mL)"], ["Milk","About 0.5 to 1 oz, and mostly foam. Stretch a small jug, let it settle a moment, then spoon or drop a single dollop onto the middle of the shot. Silky and wet, never stiff, and it should sit as a visible mark rather than stirring itself in"], ["Glass","Warmed demitasse at the 3 oz end, since a double marked with a full ounce of milk crowds a 2 oz cup"], ["Serve","Milk at 140 to 150F, the shot fresh underneath it, and out inside thirty seconds so the mark is still a mark and not a cloud"], ["Tastes like","Espresso with the sharp edge knocked off, a soft dairy note through the middle, and a finish that is still clearly coffee"], ["Sells to","To the guest who finds espresso too harsh but will not be seen ordering a cappuccino, and in Italy as the usual way to take milk after a meal, where a cappuccino is a morning drink"]] },
  { dom:"milk", name:"Cortado", cat:"With Milk", note:"Cortar means to cut, and the milk is there to cut the acid, not to make a small latte. What separates them is texture and heat: barely any foam, and milk steamed cooler on purpose so the drink is at drinking temperature the moment it lands. Steam it to latte heat and latte texture and you have built a four ounce latte in a nice glass, which is a different drink.",
    facts:[["Ratio","A double, 18 to 20 g in, 36 to 40 g out, 25 to 30 seconds, then milk. There are two builds behind the one name and they are not the same drink. The Spanish cut is a single with roughly its own volume again in milk, about 1 to 1. The American Gibraltar build puts a double under milk to fill the glass, which lands nearer 1 to 2, because there the glass sets the milk and not the ratio."], ["Volume","2 to 3 oz (60 to 90 mL) for the Spanish cut, 4 to 4.5 oz (120 to 135 mL) filled into a Gibraltar"], ["Milk","About 1 to 1.5 oz behind a single, or 2.5 to 3 oz behind a double to fill a Gibraltar. Warmed and barely textured either way: wet, glossy, a skin of foam rather than a layer, well under an eighth of an inch, pouring flat out of the jug"], ["Glass","The 4.5 oz Gibraltar glass, a small straight tumbler with no handle. Some bars use a 4 oz glass cup, and Spanish bars a smaller one again"], ["Serve","Milk to about 130 to 140F, deliberately cooler than the 140 to 150F you steam for a latte, so it goes down in three or four mouthfuls while it is still right. Straight to the guest, no saucer required"], ["Tastes like","Espresso still in front, milk sitting behind it rounding the acid rather than covering it. Sweet, short, and no cap to chew through"], ["Sells to","Mid-afternoon, to the guest who wants milk but not a mouthful of foam, and hard to the specialty regulars who order it by name"]] },
  { dom:"milk", name:"Piccolo", cat:"With Milk", note:"A piccolo is a small latte and a cortado is not, which is the reverse of how most people guess. The piccolo is textured and poured exactly like a latte, foam and pattern and all, just scaled down. The cortado is cut flatter and cooler. Neither has a fixed spec: piccolo is a trade name out of Australian cafes, so ask your own bar what its glass holds.",
    facts:[["Ratio","A single ristretto is the traditional build for a piccolo latte, roughly 9 to 10 g in for about 15 to 20 g out, call it 0.5 to 0.7 oz, in 20 to 25 seconds. Pull that to a full ounce and you have a normale, not a ristretto. Most bars own double baskets only, so a split double or a short double is the working answer, and the range is which basket you have."], ["Volume","3 to 4 oz (90 to 120 mL)"], ["Milk","About 2.5 to 3 oz to fill the glass, steamed to full latte texture: glossy microfoam, a thin cap under about a quarter inch, free-poured so it carries a small pattern. More milk relative to coffee than a cortado, in a smaller glass than a flat white"], ["Glass","A 3 to 4 oz latte glass, straight sided and no handle"], ["Serve","Milk at 140 to 150F into a warmed glass, then out immediately. At this size the surface is large against the liquid under it, so it cools fast and it is a walk rather than a wait on the pass"], ["Tastes like","A latte compressed. Milky and sweet, coffee still readable underneath, finished in four sips"], ["Sells to","To baristas, and to the guest tasting your house espresso with milk before committing to a bigger cup. Also the afternoon order for anyone who has already had two"]] },
  { dom:"milk", name:"Flat White", cat:"With Milk", note:"Flat does not mean no foam. It means no dry cap. A flat white is textured milk all the way down with a thin glossy layer folded through it, and the coffee sits further forward than in a latte simply because the cup is smaller. Be honest that the borders move: the small cup is the one constant, while the ristretto base is a common habit and several large chains define the drink by shot count instead.",
    facts:[["Ratio","A double, 18 to 20 g in, 36 to 40 g out, 25 to 30 seconds, though many New Zealand bars and some Australian ones pull a double ristretto instead for a shorter, sweeter base. Milk fills the rest of a 5 to 6 oz cup, so roughly 1 part espresso to 3 or 4 parts milk depending on the cup and the pull. The range is national habit, not error."], ["Volume","5 to 6 oz (150 to 180 mL)"], ["Milk","About 4 to 4.5 oz, stretched only briefly and then rolled until the jug is smooth and glossy with no bubbles you can see. The foam layer is thin, under about a quarter inch, and folded through the milk rather than sitting on top of it. Paint, not meringue"], ["Glass","Warmed 5 to 6 oz tulip cup with a handle"], ["Serve","Milk at 140 to 150F, poured from height at first so it sinks under the crema and mixes, then close to the surface for the pattern. Filled to the rim and out with the art facing the guest"], ["Tastes like","Coffee forward and sweet, velvety rather than airy, the milk carrying the shot instead of burying it"], ["Sells to","To Australian and New Zealand guests, to specialty regulars, and to anyone who tells you a latte is too milky and a cappuccino too foamy"]] },
  { dom:"milk", name:"Cappuccino", cat:"With Milk", note:"One third espresso, one third milk, one third foam is a teaching phrase, not a measurement, and nobody behind a bar in Italy is measuring it. What actually separates a cappuccino from a flat white at the same volume is air: you stretch longer, start with less milk in the jug, and the drink eats lighter. How thick the cap sits is house tradition. Big dry bubbles and foam separating from the milk are the real fault.",
    facts:[["Ratio","A double, 18 to 20 g in, 36 to 40 g out, 25 to 30 seconds, then milk to fill a 5 to 6 oz cup. The Italian certified spec is built on a single instead, commonly quoted as about 0.8 oz of espresso under about 3.4 oz of milk measured before it is frothed. The range is which tradition your bar follows."], ["Volume","5 to 6 oz (150 to 180 mL)"], ["Milk","About 3 to 3.5 oz in the jug, less than you would start with for a flat white in the same cup, because you stretch this one longer and it gains real volume on the way. Roll it smooth after. The cap runs about a third to a half inch, glossy and wet enough to pour through. Traditional foam sits thicker, specialty foam wetter"], ["Glass","Warmed 5 to 6 oz cup with a handle, on a saucer"], ["Serve","Milk at 140 to 150F, poured to the rim, dusted with cocoa only if the house does that. Out fast, because the cap starts drying the moment the drink stops moving"], ["Tastes like","Sweet and airy, coffee cutting up through the middle, a lighter mouthful than a flat white at the same volume because there is air in it"], ["Sells to","Mornings, and to anyone who wants something to sip slowly. The default order from the guest who does not know what to order"]] },
  { dom:"milk", name:"Latte", cat:"With Milk", note:"Order a latte in Italy and you get a glass of milk; the words you want are caffè latte. Behind the bar, the bigger error is reading latte art as proof of quality. Art tells you the milk was textured well and tells you nothing at all about the shot, and a clean rosetta on a sour, under-extracted double is still a bad drink. Taste the espresso first. Pour second.",
    facts:[["Ratio","A double, 18 to 20 g in, 36 to 40 g out, 25 to 30 seconds, then milk to fill. That works out around 1 part espresso to 5 or more parts milk at 8 oz and up, and nearer 1 to 4 in a 6 oz cup. The range is entirely cup size, which is why a 12 oz latte tastes weaker than an 8 oz one off the identical shot."], ["Volume","8 to 12 oz (240 to 355 mL), and some bars serve 6 oz (180 mL)"], ["Milk","About 6.5 to 10.5 oz depending on the cup, stretched briefly and rolled long until it is glossy and pourable with a thin foam layer around a quarter inch. Less air than a cappuccino, a touch more than a flat white, and smooth enough to hold a pattern"], ["Glass","Warmed 8 to 12 oz cup or a tall glass, handle either way"], ["Serve","Milk at 140 to 150F. Do not push past 160F even when the guest asks for it extra hot, because the sweetness reads lower against the cooked note and the milk starts to smell of it. Poured to the rim, art up"], ["Tastes like","Mild and sweet, milk in front, coffee sitting behind it as a background note. Comfortable rather than intense"], ["Sells to","All day and to everybody, and it is the base under every flavoured drink on your menu"]] },
  { dom:"milk", name:"Mocha", cat:"With Milk", note:"The name is a place, not a flavour. Mokha was the Yemeni port that shipped coffee for centuries, and the beans moving through it carried a cocoa note in the cup, so the word meant coffee long before it meant chocolate. Actual chocolate joined the drink much later. The practical end of it: stir the chocolate into the hot shot before the milk goes in, or it sets in the bottom of the cup.",
    facts:[["Ratio","A double, 18 to 20 g in, 36 to 40 g out, 25 to 30 seconds, then chocolate, then milk to fill. Around 0.75 to 1 oz of sauce is the common house pour, roughly two pumps on most bottles, but sauces differ wildly in sugar and pumps differ in volume, and powders differ more again. Taste yours neat and set the dose against your own cup rather than copying a number."], ["Volume","8 to 12 oz (240 to 355 mL)"], ["Milk","About 6 to 9.5 oz depending on the cup, at latte texture, glossy with a thin foam layer. Run it slightly wetter than a plain latte, because the chocolate brings body of its own and a stiff cap sitting on sauce eats like pudding"], ["Glass","Warmed 8 to 12 oz cup or a tall glass; clear glass if the house builds it in visible layers"], ["Serve","Milk at 140 to 150F, same ceiling as a latte. Whipped cream and a dusting go on last and only if the house does them. Out quickly, because chocolate sinks"], ["Tastes like","Sweet and rich, cocoa in front, coffee arriving underneath it, and a finish that depends entirely on how bitter your chocolate is"], ["Sells to","To the guest who does not really like coffee, to the late table that wants dessert in a cup, and to most of the room at eleven at night"]] },
];
